"""add account, session, diagnosis, favorite tables

Revision ID: 878a1a776a54
Revises: fb447585b208
Create Date: 2026-09-11 15:10:41.764862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '878a1a776a54'
down_revision: Union[str, None] = 'fb447585b208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('diagnoses',
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('building_type_key', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('confirmed_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculation_version', sa.String(), nullable=False),
    sa.Column('reference_data_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_table('sessions',
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_token')
    )
    op.create_table('favorites',
    sa.Column('favorite_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.diagnosis_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    # 주의: users/diagnoses/sessions/favorites 테이블 생성 외에 아무 것도 건드리지 않는다.
    # autogenerate가 fb447585b208에서 raw SQL(op.create_index)로만 만든 partial unique
    # index 3개(모델 메타데이터에는 선언되지 않음)를 삭제 대상으로 오인했으나, 이 인덱스들은
    # db-spec.md 4.3의 필수 제약이므로 여기서 지우면 안 된다 — autogenerate 결과에서 제외함.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('sessions')
    op.drop_table('diagnoses')
    op.drop_table('users')
    # ### end Alembic commands ###
