"""create reference data schema

Revision ID: fb447585b208
Revises: 
Create Date: 2026-09-11 13:13:19.558695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb447585b208'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_components',
    sa.Column('component_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('component_key')
    )
    op.create_table('calculation_policies',
    sa.Column('calculation_policy_id', sa.UUID(), nullable=False),
    sa.Column('formula_version', sa.String(), nullable=False),
    sa.Column('result_message_policy_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('calculation_policy_id'),
    sa.UniqueConstraint('formula_version')
    )
    op.create_table('climate_zones',
    sa.Column('climate_zone_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('climate_zone_key')
    )
    op.create_table('construction_year_ranges',
    sa.Column('construction_year_range_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('start_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('construction_year_range_key')
    )
    op.create_table('insulation_statuses',
    sa.Column('insulation_status_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('insulation_status_key')
    )
    op.create_table('reference_documents',
    sa.Column('reference_document_id', sa.UUID(), nullable=False),
    sa.Column('reference_name', sa.String(), nullable=False),
    sa.Column('notice_number', sa.String(), nullable=True),
    sa.Column('reference_version', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('reference_document_id'),
    sa.UniqueConstraint('reference_name', 'reference_version', name='uq_reference_documents_name_version')
    )
    op.create_table('target_u_value_building_groups',
    sa.Column('building_group_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('building_group_key')
    )
    op.create_table('building_type_target_group_mappings',
    sa.Column('building_type_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('building_group_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['building_group_key'], ['target_u_value_building_groups.building_group_key'], ),
    sa.PrimaryKeyConstraint('building_type_key')
    )
    op.create_table('calculation_result_message_policies',
    sa.Column('calculation_result_message_id', sa.UUID(), nullable=False),
    sa.Column('calculation_policy_id', sa.UUID(), nullable=False),
    sa.Column('message_key', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_policy_id'], ['calculation_policies.calculation_policy_id'], ),
    sa.PrimaryKeyConstraint('calculation_result_message_id'),
    sa.UniqueConstraint('calculation_policy_id', 'message_key', name='uq_calculation_result_message_policies_policy_key')
    )
    op.create_table('calculation_scenarios',
    sa.Column('calculation_scenario_id', sa.UUID(), nullable=False),
    sa.Column('calculation_policy_id', sa.UUID(), nullable=False),
    sa.Column('scenario_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_policy_id'], ['calculation_policies.calculation_policy_id'], ),
    sa.PrimaryKeyConstraint('calculation_scenario_id'),
    sa.UniqueConstraint('calculation_policy_id', 'scenario_key', name='uq_calculation_scenarios_policy_key')
    )
    op.create_table('current_wall_u_value_policies',
    sa.Column('current_wall_u_policy_id', sa.UUID(), nullable=False),
    sa.Column('construction_year_range_key', sa.String(), nullable=False),
    sa.Column('insulation_status_key', sa.String(), nullable=False),
    sa.Column('u_value_w_m2k', sa.Numeric(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('reference_document_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('u_value_w_m2k > 0', name='ck_current_wall_u_value_policies_positive'),
    sa.ForeignKeyConstraint(['construction_year_range_key'], ['construction_year_ranges.construction_year_range_key'], ),
    sa.ForeignKeyConstraint(['insulation_status_key'], ['insulation_statuses.insulation_status_key'], ),
    sa.ForeignKeyConstraint(['reference_document_id'], ['reference_documents.reference_document_id'], ),
    sa.PrimaryKeyConstraint('current_wall_u_policy_id'),
    sa.UniqueConstraint('construction_year_range_key', 'insulation_status_key', 'policy_version', name='uq_current_wall_u_value_policies')
    )
    op.create_table('current_window_u_value_policies',
    sa.Column('current_window_u_policy_id', sa.UUID(), nullable=False),
    sa.Column('window_type_key', sa.String(), nullable=False),
    sa.Column('low_e_key', sa.String(), nullable=False),
    sa.Column('u_value_w_m2k', sa.Numeric(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('reference_document_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('u_value_w_m2k > 0', name='ck_current_window_u_value_policies_positive'),
    sa.ForeignKeyConstraint(['reference_document_id'], ['reference_documents.reference_document_id'], ),
    sa.PrimaryKeyConstraint('current_window_u_policy_id'),
    sa.UniqueConstraint('window_type_key', 'low_e_key', 'policy_version', name='uq_current_window_u_value_policies')
    )
    op.create_table('hdd_values',
    sa.Column('hdd_lookup_key', sa.String(), nullable=False),
    sa.Column('hdd_value_k_day', sa.Numeric(), nullable=False),
    sa.Column('reference_document_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('hdd_value_k_day > 0', name='ck_hdd_values_positive'),
    sa.ForeignKeyConstraint(['reference_document_id'], ['reference_documents.reference_document_id'], ),
    sa.PrimaryKeyConstraint('hdd_lookup_key')
    )
    op.create_table('calculation_scenario_components',
    sa.Column('calculation_scenario_id', sa.UUID(), nullable=False),
    sa.Column('component_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_scenario_id'], ['calculation_scenarios.calculation_scenario_id'], ),
    sa.ForeignKeyConstraint(['component_key'], ['building_components.component_key'], ),
    sa.PrimaryKeyConstraint('calculation_scenario_id', 'component_key')
    )
    op.create_table('supported_regions',
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('hdd_lookup_key', sa.String(), nullable=False),
    sa.Column('climate_zone_key', sa.String(), nullable=False),
    sa.Column('region_data_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['climate_zone_key'], ['climate_zones.climate_zone_key'], ),
    sa.ForeignKeyConstraint(['hdd_lookup_key'], ['hdd_values.hdd_lookup_key'], ),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('target_u_value_policies',
    sa.Column('target_u_policy_id', sa.UUID(), nullable=False),
    sa.Column('building_group_key', sa.String(), nullable=False),
    sa.Column('component_key', sa.String(), nullable=False),
    sa.Column('climate_zone_key', sa.String(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=True),
    sa.Column('appendix_identifier', sa.String(), nullable=False),
    sa.Column('condition_description', sa.Text(), nullable=False),
    sa.Column('u_value_w_m2k', sa.Numeric(), nullable=False),
    sa.Column('reference_document_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(climate_zone_key IS NOT NULL) <> (region_id IS NOT NULL)', name='ck_target_u_value_policies_scope_xor'),
    sa.CheckConstraint('u_value_w_m2k > 0', name='ck_target_u_value_policies_positive'),
    sa.ForeignKeyConstraint(['building_group_key'], ['target_u_value_building_groups.building_group_key'], ),
    sa.ForeignKeyConstraint(['climate_zone_key'], ['climate_zones.climate_zone_key'], ),
    sa.ForeignKeyConstraint(['component_key'], ['building_components.component_key'], ),
    sa.ForeignKeyConstraint(['reference_document_id'], ['reference_documents.reference_document_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['supported_regions.region_id'], ),
    sa.PrimaryKeyConstraint('target_u_policy_id')
    )

    # db-spec.md 4.3: supported_regions 목록 조회용 인덱스
    op.create_index('ix_supported_regions_is_supported', 'supported_regions', ['is_supported'])

    # db-spec.md 4.3: target_u_value_policies 부분 UNIQUE 인덱스 (기후구역 범위 / 지원 지역 범위 각각 유일)
    op.create_index(
        'uq_target_u_value_policies_climate_scope',
        'target_u_value_policies',
        ['building_group_key', 'component_key', 'climate_zone_key', 'appendix_identifier', 'condition_description', 'reference_document_id'],
        unique=True,
        postgresql_where=sa.text('climate_zone_key IS NOT NULL'),
    )
    op.create_index(
        'uq_target_u_value_policies_region_scope',
        'target_u_value_policies',
        ['building_group_key', 'component_key', 'region_id', 'appendix_identifier', 'condition_description', 'reference_document_id'],
        unique=True,
        postgresql_where=sa.text('region_id IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_target_u_value_policies_region_scope', table_name='target_u_value_policies')
    op.drop_index('uq_target_u_value_policies_climate_scope', table_name='target_u_value_policies')
    op.drop_index('ix_supported_regions_is_supported', table_name='supported_regions')
    op.drop_table('target_u_value_policies')
    op.drop_table('supported_regions')
    op.drop_table('calculation_scenario_components')
    op.drop_table('hdd_values')
    op.drop_table('current_window_u_value_policies')
    op.drop_table('current_wall_u_value_policies')
    op.drop_table('calculation_scenarios')
    op.drop_table('calculation_result_message_policies')
    op.drop_table('building_type_target_group_mappings')
    op.drop_table('target_u_value_building_groups')
    op.drop_table('reference_documents')
    op.drop_table('insulation_statuses')
    op.drop_table('construction_year_ranges')
    op.drop_table('climate_zones')
    op.drop_table('calculation_policies')
    op.drop_table('building_components')
    # ### end Alembic commands ###
